@startgantt
project starts the 2020/08/18

[Design du prototype] starts 2020-08-18 and ends 2020-08-31

[Run] lasts 14 days
[Mysql] lasts 14 days
[Mysql1] lasts 14 days
[Mysql2] lasts 14 days
[Mysql3] lasts 14 days

@endgantt