@startmindmap
* Interview
** HashMap
** HashTable
** HashTable
** Redis
** ConcurrentHashMap
** ConcurrentHashMap
** ThreadLocal
** MySQL 三万字精华总结 + 面试100 问，和面试官扯皮绰绰有余（收藏系列） https://juejin.im/post/5f0d4fadf265da22f3250eaa#heading-9
** 一个月面了几家大厂 总结了5W字的后端面经（持续更新）https://juejin.im/post/6844904161612398600
** 死磕synchronized底层实现 https://juejin.im/post/6844904196676780040
@endmindmap