@startmindmap

* TS
** JDK
** JVM
** Algorithm&DataStructure
** Docker&K8S
** Spring
*** Spring
*** SpringBoot
*** SpringCloud
*** SpringCloud Alibaba
** MQ
** NoSQL
*** Redis
**** 1.ADB&ROF 持久化机制
**** 2.ADB&ROF 持久化机制
**** 3.ADB&ROF 持久化机制

** MySQL

left side


** JDK
** JVM
** Algorithm&DataStructure
** Docker&K8S
** Spring
*** Spring
*** SpringBoot
*** SpringCloud
*** SpringCloud Alibaba
** MQ
** NoSQL
*** Redis
**** 1.ADB&ROF 持久化机制
**** 2.ADB&ROF 持久化机制
**** 3.ADB&ROF 持久化机制
@endmindmap
