@startmindmap
* PM
** 程序员做项目管理的三大误区
*** 误区1:凡是恨不得事必躬亲
*** 误区2:追在别人屁股后面做监工
*** 误区3:拿着锤子,看哪里都是钉子
** 十大领域
*** 整合管理
*** 范围管理
*** 进度管理
*** 成本管理
*** 质量管理
*** 资源管理
*** 沟通管理
*** 风险管理
*** 采购管理
*** 相关方管理
** 五大工程组
*** 启动
**** 四类干系人
***** 高权力高利益
***** 高权力低利益
***** 低权力高利益
***** 低权力低利益
*** 规划
**** 规划雷区
***** 雷区一：不够具体:拆分:做计划的方式的转变，背后其实是思维方式的根本转变
***** 雷区二：不够全面:识别依赖并画出关键路径
***** 雷区三：不够准确:做计划的第三个标准动作了，就是定义完成标准
***** 雷区四：没有共识:达成共识并公开透明，就是做计划的第四个标准动作
***** 雷区五：不够及时:及时调整变更
*** 执行
**** 闭环
***** 方案评审（OARP 决策机制）
***** Bug Bash
***** 冒烟用例评审
*** 监控
**** 紧急报告
***** 事件描述
***** 影响后果
***** 跟进分析
***** 响应措施
***** 所需支持
**** 常规汇报
**** 数据汇报
*** 收尾
**** 复盘会的基调设定
**** 复盘会的会前准备
**** 复盘会的简易流程
**** 打造团队持续改进能力
** 生命周期阶段治理
*** 启动项目
*** 组织与准备
*** 执行项目工作
*** 结束项目
*** 需求变更
**** 锦囊 1：达成最小共识，变更是有代价的
**** 锦囊 2：源头治理，一次把事情做对
**** 锦囊 3：快试错，不可抗力巧应对
*** 风险管理
**** 1. 治未病，建立系统性保健机制
**** 2. 积极管理致命风险
**** 2. 积极管理致命风险
*** 高效会议
**** 0.启动会
**** 1.每日站会
**** 2.项目周会
*** 会议规则
**** 1. 明确会议边界
**** 2. 建立会议规则
**** 3. 做好会后跟进

*** 向上管理
**** 误区1：所有问题都自己扛
**** 误区2：只知道吐槽，不知道争取
**** 误区3：抓不住重点，给不出方案
*** 跨部门沟通
**** 第一步：建立君子协定
**** 第二步：建立机制
**** 第三步：解决问题
*** 非职权沟通
**** 执行力
**** 信息力
**** 感知力
**** 透明力
**** 影响力
**** 整合力
*** PMP
**** 3,6,9,12




@endmindmap